### ISSUE TITLE
restrict search to a specific path

### ISSUE THREAD

**Issue by anarcat** [ceigh/git-hours#1]
being able to pass a repository is nice, but it's actually surprising: git already supports acting on different repositories with the `-C` parameter so the argument feels superfluous.

i expected the `path` argument to be a path *inside the repository* to limit the search to. this is how this python implementation does it, FWIW:

https://gist.githubusercontent.com/leandropls/6db26df3939b094dd321/raw/1e0424aa9c2925e77cde4221565fb114dc93fc83/git-hours.py

**Comment by ceigh** [comment]
Hey @anarcat! Thank you for the first issue  here.
The approach you described using the `-C` key sounds more idiomatic.
But if we use a binary without binding to the `git` (as a standalone program), we will not be able to get the necessary functionality.
In anyway, I also think that this is how it should be, so in the next release I will remove the path parameter to the repository completely.

**Comment by ceigh** [comment]
https://github.com/ceigh/git-hours/releases/tag/2.0.0

**Comment by anarcat** [comment]
another way to do `-C` is to set GIT_DIR, I believe.

that said, the point of this issue was more a feature request, which was to support restricting the search to a single path in the repository.

say, for example, i want to see how long it took only to write `git-hours.c`, without the rest of the repository here. how would i proceed?

**Comment by ceigh** [comment]
@anarcat 
I think it's possible, but the implementation will be a bit tricky.
Need to look at the libgit documentation.

The first thing that comes to mind is to filter commits by checking the tree of each for the presence of the desired file.
I think this is a little bit too much..

https://libgit2.org/libgit2/#HEAD/group/commit/git_commit_tree
https://libgit2.org/libgit2/#HEAD/group/tree/git_tree_walk
https://libgit2.org/libgit2/#HEAD/group/tree/git_tree_entry_byname

But I like the idea, so one of these days I'll try to implement something similar.

**Comment by anarcat** [comment]
the python implementation doesn't use libgit but talks directly with `git-log`. it uses the `--shortstat` option to get a list of changed files and discards commits that do not feature the requested path...

so yes, basically, you need to check the tree (but only that, no need to start expanding blobs)... so it's just one reference away from the commit, not that bad....

**Comment by ceigh** [comment]
@anarcat  Hello again. So now it is `2.1.1` with support for specific file in repository:

```shell
git hours file_name
me@org.com    6    9
```
(slow on repositories with huge amount of commits)

Let me know what you think ;)

**Comment by anarcat** [comment]
great! that's pretty much what i wanted, thanks! :)
